#!/bin/bash

yml_file=codingame.yml

add_all() {
    for file in $@; do
        echo git add "$file"
        git add "$file"
	sleep 0.2
    done
}

IFS=$'\n'
add_all $(./embed_examples.pl $yml_file)
add_all $(./sanitize_projects.pl $yml_file)
unset IFS
