#!/bin/bash

yml_file=codingame.yml

add_all() {
    IFS=$'\n'
    for file in $1; do
        git add "$file"
    done
}

add_all $(./embed_examples.pl $yml_file)
add_all $(./sanitize_projects.pl $yml_file)
